name: Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy-Render:
    runs-on: ubuntu-latest
    steps:
      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v0.8.6/cli_0.8.6_linux_amd64.zip -o render.zip
          unzip render.zip
          sudo mv cli_v0.8.6 /usr/local/bin/render

      - name: Authenticate with Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render login --output json

      - name: Deploy and Wait for All Services
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          set -e

          # Create deployments and capture deployment IDs
          DEPLOY_ID_1=$(render deploys create ${{ secrets.RENDER_SERVICE_ID }} --output json --confirm | jq -r '.id')
          DEPLOY_ID_2=$(render deploys create ${{ secrets.RENDER_DATA_SYNCER_SERVICE_ID }} --output json --confirm | jq -r '.id')
          DEPLOY_ID_3=$(render deploys create ${{ secrets.RENDER_SERVICE_ID_DEV }} --output json --confirm | jq -r '.id')
          DEPLOY_ID_4=$(render deploys create ${{ secrets.RENDER_DATA_SYNCER_SERVICE_ID_DEV }} --output json --confirm | jq -r '.id')

          echo "Waiting for deployments to finish..."

          render deployments wait "$DEPLOY_ID_1"
          render deployments wait "$DEPLOY_ID_2"
          render deployments wait "$DEPLOY_ID_3"
          render deployments wait "$DEPLOY_ID_4"

          echo "Done"
