name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Deploy-Vercel:
    if: false
    #Temporarily disabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  Deploy-Render:
    runs-on: ubuntu-latest
    steps:
      - name: Install Render CLI
        run: |
          curl -L https://github.com/renderinc/render-cli/releases/download/v0.1.0/render-cli-v0.1.0-linux-amd64.tar.gz -o render-cli.tar.gz
          tar -xzf render-cli.tar.gz
          sudo mv render /usr/local/bin/
      - name: Authenticate with Render
        run: render login --api-key ${{ secrets.RENDER_API_KEY }}
      - name: Trigger Render Deployment
        run: render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }}
