name: Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy-Render:
    runs-on: ubuntu-latest
    steps:
      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v2.1.1/cli_2.1.1_linux_amd64.zip -o render.zip
          unzip render.zip
          sudo mv cli_v2.1.1 /usr/local/bin/render

      - name: Authenticate with Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render login --output json

      - name: Deploy and Wait for All Services in Parallel
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          set -e

          deploy() {
            SERVICE_ID=$1
            echo "Starting deployment for service $SERVICE_ID"
            render deploys create "$SERVICE_ID" --output json --confirm --wait
            echo "✅ Deployment for $SERVICE_ID completed"
          }

          # Start all deployments in parallel
          deploy "${{ secrets.RENDER_SERVICE_ID }}" &
          PID1=$!

          deploy "${{ secrets.RENDER_DATA_SYNCER_SERVICE_ID }}" &
          PID2=$!

          deploy "${{ secrets.RENDER_SERVICE_ID_DEV }}" &
          PID3=$!

          deploy "${{ secrets.RENDER_DATA_SYNCER_SERVICE_ID_DEV }}" &
          PID4=$!

          # Wait for all to finish
          wait $PID1
          wait $PID2
          wait $PID3
          wait $PID4

          echo "✅ All deployments finished"
