name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Deploy-Vercel:
    if: false
    #Temporarily disabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  Deploy-Render:
    runs-on: ubuntu-latest
    steps:
      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v0.8.5/cli_0.8.5_linux_amd64.zip -o render.zip
          unzip render.zip
          sudo mv cli_v0.8.5 /usr/local/bin/render
      - name: Authenticate with Render
        run: render login
      - name: Trigger Render Deployment
        run: render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }}
